### ISSUE TITLE
小程序dropdown-menu下拉菜单报错X(D.utils).bem is not a function

### ISSUE THREAD

**Issue by scancode911** [vant-ui/vant-demo#115]
1.10.23 应该不是包出问题了, 换个小程序引用没问题. 实在找不出来是什么原因导致的
![381ccd1e6ed3d5942a3d7023410a01c](https://github.com/vant-ui/vant-demo/assets/105727286/f1bcada6-d5a7-43b0-b5cb-e3d3b19bbcb4)

**Comment by dunan-01** [comment]
你解决了吗

**Comment by scancode911** [comment]
> 你解决了吗

解决了 详见https://github.com/youzan/vant-weapp/issues/5522#issuecomment-1683369348

**Comment by dunan-01** [comment]
> > 你解决了吗
> 
> 解决了 详见[youzan/vant-weapp#5522 (comment)](https://github.com/youzan/vant-weapp/issues/5522#issuecomment-1683369348)

好的，十分感谢，我也解决了
