### ISSUE TITLE
clone 安装 vant-demo/vant-Weapp出错，资源已转移？

### ISSUE THREAD

**Issue by jacky-peng-cn** [vant-ui/vant-demo#122]
如题：

PS D:\Dev\vant\vant-demo\vant-weapp\base> npm -v
9.8.1
PS D:\Dev\vant\vant-demo\vant-weapp\base> npm i
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://registry.npm.qima-inc.com/@vant/weapp/download/@vant/weapp-1.0.0.tgz failed, reason: connect ETIMEDOUT 10.11.1.51:80, reason: connect ETIMEDOUT 10.11.1.51:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

详见下图。
![1698032231512](https://github.com/vant-ui/vant-demo/assets/61534961/f6f24fdc-e6e8-4de4-bfcf-f2c80b2d93d6)

**Comment by chenjiahan** [comment]
把 registry.npm.qima-inc.com 换成 registry.npmjs.org 试试

**Comment by jacky-peng-cn** [comment]
感谢提醒，还以为是有赞的私链。
官方链接不行，但国内 mirror 通过。
![1698034957570](https://github.com/vant-ui/vant-demo/assets/61534961/3f6c19cc-6b29-4d77-90ca-f4206836491b)
