### ISSUE TITLE
vite按需引入报错：Failed to resolve import "vant/es" from "src/App.vue". Does the file exist?

### ISSUE THREAD

**Issue by strayark** [vant-ui/vant-demo#132]
报错信息-截图：
![image](https://github.com/user-attachments/assets/e86108db-3c90-4981-8ee1-daee1d66d972)

报错信息-文字：
[plugin:vite:import-analysis] Failed to resolve import "vant/es" from "src/App.vue". Does the file exist?
D:/Code/vue/vue3/projects/02_bilibili_mobile/src/App.vue:1:91
1  |  /* unplugin-vue-components disabled */import { tButton as __unplugin_components_0 } from 'vant/es';import 'vant/es/t-button/style/index';
   |                                                                                            ^
2  |  /* Injection by vite-plugin-vue-inspector Start */
3  |  import { createVNode as __createVNode,createElementBlock as __createElementBlock } from 'vue'
    at TransformPluginContext._formatError (file:///D:/Code/vue/vue3/projects/02_bilibili_mobile/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:47166:41)
    at TransformPluginContext.error (file:///D:/Code/vue/vue3/projects/02_bilibili_mobile/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:47161:16)
    at normalizeUrl (file:///D:/Code/vue/vue3/projects/02_bilibili_mobile/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:45431:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///D:/Code/vue/vue3/projects/02_bilibili_mobile/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:45550:39
    at async Promise.all (index 0)
    at async TransformPluginContext.transform (file:///D:/Code/vue/vue3/projects/02_bilibili_mobile/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:45477:7)
    at async file:///D:/Code/vue/vue3/projects/02_bilibili_mobile/node_modules/vite-plugin-vue-devtools/node_modules/vite-plugin-inspect/dist/index.mjs:1120:17
    at async EnvironmentPluginContainer.transform (file:///D:/Code/vue/vue3/projects/02_bilibili_mobile/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:47009:18)
    at async loadAndTransform (file:///D:/Code/vue/vue3/projects/02_bilibili_mobile/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:40848:27
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.ts.

代码：
**vite.config.js:**

`import { fileURLToPath, URL } from 'node:url';

import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueDevTools from 'vite-plugin-vue-devtools';
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { VantResolver } from '@vant/auto-import-resolver'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vueDevTools(),
    AutoImport({
      resolvers: [VantResolver()],
    }),
    Components({
      resolvers: [VantResolver()],
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
  }
});
`

**App.vue:**
(粘贴的代码不知道为什么展示不出来，直接上截图了)
![image](https://github.com/user-attachments/assets/39d2e383-6752-4702-82b7-a26e9ef03bf2)

**package.json:**
`{
  "name": "02_bilibili_mobile",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "run-p type-check \"build-only {@}\" --",
    "preview": "vite preview",
    "build-only": "vite build",
    "type-check": "vue-tsc --build",
    "lint": "eslint . --fix",
    "format": "prettier --write src/"
  },
  "dependencies": {
    "normalize.css": "^8.0.1",
    "vant": "^4.9.9",
    "vue": "^3.5.13",
    "vue-router": "^4.4.5"
  },
  "devDependencies": {
    "@tsconfig/node22": "^22.0.0",
    "@types/node": "^22.9.3",
    "@vant/auto-import-resolver": "^1.2.1",
    "@vitejs/plugin-vue": "^5.2.1",
    "@vue/eslint-config-prettier": "^10.1.0",
    "@vue/eslint-config-typescript": "^14.1.3",
    "@vue/tsconfig": "^0.7.0",
    "eslint": "^9.14.0",
    "eslint-plugin-vue": "^9.30.0",
    "less": "^4.2.1",
    "less-loader": "^12.2.0",
    "npm-run-all2": "^7.0.1",
    "prettier": "^3.3.3",
    "typescript": "~5.6.3",
    "unplugin-auto-import": "^0.18.6",
    "unplugin-vue-components": "^0.27.5",
    "vite": "^6.0.1",
    "vite-plugin-vue-devtools": "^7.6.5",
    "vue-tsc": "^2.1.10"
  }
}
`
![image](https://github.com/user-attachments/assets/8cea72d4-58a0-4c41-afc5-271d87881d62)

**Comment by Liu-Yuan-Bo** [comment]
meeto

**Comment by Liu-Yuan-Bo** [comment]
vite.config.js中resolve.extensions 增加.mjs
extensions: ['.mjs', '.js', '.ts', '.jsx', '.tsx', '.json', '.vue'],
